#!/bin/sh

## Copy the selected file to the correct place
#cp -f %f /home/thasharath/Pictures/.wall.jpg

## Changing the wallpaper to the backup picture
dbus-send --session --dest=org.kde.plasmashell --type=method_call /PlasmaShell org.kde.PlasmaShell.evaluateScript 'string:
var Desktops = desktops();
for (i=0;i<Desktops.length;i++) {
	d = Desktops[i];
	d.wallpaperPlugin = "org.kde.image";
	d.currentConfigGroup = Array("Wallpaper",
					"org.kde.image",
					"General");
	d.writeConfig("Image", "/home/thasharath/Pictures/.w.jpg");
}'

## Wait for three seconds
sleep 3

## Run pywal
wal -a 93 -i %f

## Changing to the proper wallpaper
dbus-send --session --dest=org.kde.plasmashell --type=method_call /PlasmaShell org.kde.PlasmaShell.evaluateScript 'string:
var Desktops = desktops();
for (i=0;i<Desktops.length;i++) {
	d = Desktops[i];
	d.wallpaperPlugin = "org.kde.image";
	d.currentConfigGroup = Array("Wallpaper",
					"org.kde.image",
					"General");
	d.writeConfig("Image", "/home/thasharath/Pictures/.wall.jpg");
}'
